paths:
- path: /tmp/suspicious-watch
- allow_parent_chains:
  - ssh,git,lazygit,zsh,.ghostty-wrappe
  path: /home/nils/.ssh
- path: /home/nils/.config/openstack
- allow_parent_chains:
  - kubectl,zsh,zsh,zsh,.ghostty-wrappe,.Hyprland-wrapp,start-hyprland,gdm-wayland-ses,gdm-session-wor,gdm,systemd
  path: /home/nils/.kube
- path: /home/nils/.gnupg
